## Question 1



In [5]:
#option 1: Addition Operator (+)

A = [1,2,3,4,5,6]
B = [13, 21, 34]
A_B = A + B
A_B

[1, 2, 3, 4, 5, 6, 13, 21, 34]

In [7]:
#option 2: Appending list B into A

A = [1,2,3,4,5,6]
B = [13, 21, 34]
for x in B:
  A.append(x)
print(A)

[1, 2, 3, 4, 5, 6, 13, 21, 34]


In [9]:
#option 3: Using extend() method to add list B to list A:

A = [1,2,3,4,5,6]
B = [13, 21, 34]
A.extend(B)
print(A)


[1, 2, 3, 4, 5, 6, 13, 21, 34]


##  Question 2

In [11]:
import numpy as np
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
identity = np.array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [20]:
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Question 3

In [22]:
import pandas as pd
fuel_data = pd.read_csv("fuel_ferc1.csv")
fuel_data.head(5)

record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
4             chickasaw                 gas       mcf          40533.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0               16.590                      18.59   
1               16.592                      18.58   
2               24.130                      39.72   
3               23.950                      47.21   
4                1.000                       2.77   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
4                          2.77                2.570

In [27]:
fuel_cost= fuel_data.groupby(["fuel_type_code_pudl"]).mean()


In [28]:
fuel_cost

utility_id_ferc1  report_year  fuel_qty_burned  \
fuel_type_code_pudl                                                   
coal                       115.637534  2004.623143     1.903473e+06   
gas                        124.122062  2005.978060     4.843183e+06   
nuclear                    107.397311  2002.970660     5.454838e+06   
oil                        113.236235  2007.195933     6.311677e+04   
other                      110.467066  2001.700599     2.948137e+06   
waste                      154.253968  2005.650794     1.171914e+05   

                     fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
fuel_type_code_pudl                                                   
coal                           20.762780                  67.421830   
gas                             1.021913                  13.659397   
nuclear                        17.582120                4955.157002   
oil                             5.814377                 168.877086   
other                           0.572752                  18.253856   
waste                           0.341163                  19.518122   

                     fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
fuel_type_code_pudl                                                     
coal                                   116.951141             1.787190  
gas                                     12.095172             5.408876  
nuclear                              28616.915039             1.716559  
oil                                    313.907691            12.698732  
other                                   16.871485           155.084910  
waste                                   18.413052           822.709937

## Question 4

In [29]:
fuel_data.describe()

utility_id_ferc1   report_year  fuel_qty_burned  fuel_mmbtu_per_unit  \
count      29523.000000  29523.000000     2.952300e+04         29523.000000   
mean         118.601836   2005.806050     2.622119e+06             8.492111   
std           74.178353      7.025483     9.118004e+06            10.600220   
min            1.000000   1994.000000     1.000000e+00             0.000001   
25%           55.000000   2000.000000     1.381700e+04             1.024000   
50%          122.000000   2006.000000     2.533220e+05             5.762694   
75%          176.000000   2012.000000     1.424034e+06            17.006000   
max          514.000000   2018.000000     5.558942e+08           341.260000   

       fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
count               29523.000000                  2.952300e+04   
mean                  208.649031                  9.175704e+02   
std                  2854.490090                  6.877593e+04   
min                  -276.080000                 -8.749370e+02   
25%                     5.207000                  3.778500e+00   
50%                    26.000000                  1.737100e+01   
75%                    47.113000                  4.213700e+01   
max                139358.000000                  7.964521e+06   

       fuel_cost_per_mmbtu  
count         29523.000000  
mean             19.304354  
std            2091.540939  
min             -41.501000  
25%               1.940000  
50%               4.127000  
75%               7.745000  
max          359278.000000

## Question 10

In [30]:
fuel_year= fuel_data.groupby(["report_year"]).mean()


In [31]:
fuel_year

utility_id_ferc1  fuel_qty_burned  fuel_mmbtu_per_unit  \
report_year                                                           
1994               106.120648     2.724018e+06            10.638098   
1995               110.139051     3.712067e+06            10.644830   
1996               108.714154     2.544754e+06            10.778041   
1997               108.366545     2.813503e+06            10.247632   
1998               109.845528     3.267453e+06            10.704964   
1999               108.222857     3.281281e+06            10.558885   
2000               111.083758     2.472032e+06             9.224475   
2001               113.521386     2.321402e+06             8.371469   
2002               120.354357     2.145645e+06             8.304833   
2003               123.300578     1.888622e+06             8.403746   
2004               121.123322     1.782547e+06             8.332425   
2005               121.028369     1.768876e+06             8.135972   
2006               117.178600     1.957264e+06             8.138090   
2007               116.040348     2.035696e+06             8.027581   
2008               120.785016     2.046455e+06             7.892854   
2009               118.139116     2.154993e+06             7.688192   
2010               117.992863     2.423720e+06             7.575013   
2011               121.069355     2.461332e+06             7.786182   
2012               120.769912     2.747094e+06             7.796063   
2013               122.082569     2.741505e+06             7.797024   
2014               129.263877     2.700008e+06             7.588334   
2015               128.591949     3.340131e+06             7.217820   
2016               133.117021     3.693289e+06             6.846478   
2017               131.126888     3.352850e+06             6.781353   
2018               133.669821     4.178890e+06             6.596546   

             fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
report_year                                                            
1994                        213.191996                     63.636060   
1995                        354.422555                     32.735269   
1996                         79.434995                   9196.705948   
1997                        149.482132                  11140.197239   
1998                        126.683519                    287.154420   
1999                        120.053605                     25.551627   
2000                        237.797111                    985.362877   
2001                        133.013010                     60.050396   
2002                        101.179365                     47.594361   
2003                        123.183919                     55.663493   
2004                        154.897398                    139.524275   
2005                        107.111221                     41.438184   
2006                        151.361249                     38.657484   
2007                        202.622082                     43.325023   
2008                        255.954415                     58.588197   
2009                        215.699318                    652.694163   
2010                        262.951203                     91.862105   
2011                        301.754519                     59.774667   
2012                        258.804138                     60.994502   
2013                        255.991023                    172.307591   
2014                        442.359068                    192.737183   
2015                        237.933197                    326.535511   
2016                        247.083959                    103.901761   
2017                        246.281796                     46.196861   
2018                        232.992036                    499.269966   

             fuel_cost_per_mmbtu  
report_year                       
1994                    3.086977  
1995                    2.868838  
1996      

## Question 5

In [ ]:
import numpy as np
from scipy.stats import kurtosis, skew

